# -*- org-attach-id-dir: "../../../../files/attachments"; -*-
#+BEGIN_COMMENT
.. title: The Lisp curse
.. slug: the-lisp-curse
.. date: 2026-06-18 10:07:24 UTC+01:00
.. tags: project:lisp-bibliography, lisp, experience
.. category:
.. link:
.. description:
.. type: text

#+END_COMMENT
* The Lisp curse

    https://www.winestockwebdesign.com/Essays/Lisp_Curse.html

    #+begin_quote
    The power of Lisp is its own worst enemy.
#+end_quote

    An interesting essay on the "Lisp curse", the idea that Lisp's
    power can sometimes be a /disadvantage/ for developers. The core
    idea expressed as a question: how hard is it to add
    object-oriented features to a language? In the C world it's
    happened twice, giving rise to C++ and Objective-C, an no-one
    would even /think/ about defining their own. In the Lisp world, by
    contrast, building that style of object-oriented extension is a
    weekend's work (assuming we didn't already have CLOS, which is in
    many ways superior anyway). The point is that it's relatively easy
    to build even complex features as libraries, meaning there's less
    reason to standardise, and this leads to a proliferation of
    mutually incompatible designs that solve 80% of the problem -- but
    all a /different/ 80%. This then makes interoperability difficult.

    In fact the essay goes farther, to argue that the sorts of people
    who write Lisp tend not to be the sorts of people of work well in
    the political and compromise-driven world of standardisation. I'm
    not sure how true that is, given the stability of the Common Lisp
    standard itself since its adoption in 1994, but it's an
    interesting reflection on how increased language expressiveness
    need not automatically be a strength.

    (Some of the links in the article are now broken, or point to what
    looks like an AI link farm.)
