# -*- org-attach-id-dir: "../../files/attachments"; -*-

* Biography                                                          :ATTACH:
  :PROPERTIES:
  :ID:       7daa1dc8-9fa5-4fac-a23c-289f697e67e9
  :END:

  Simon Dobson is Professor of Computer Science in the [[https://www.st-andrews.ac.uk/computer-science/][School of
  Computer Science]] at the [[https://www.st-andrews.ac.uk][University of St Andrews]], and was Head of
  School from 2017 -- 2021. He was elected Fellow of the [[https://www.rse.org.uk][Royal Society
  of Edinburgh]], Scotland's national academy, in 2020, and serves as a
  science adviser to the Scottish government as a member of the
  [[https://scottishscience.org.uk][Scottish Science Advisory Council]].

  Simon works on complex and sensor systems, focusing on sensor
  analytics and the modelling of complex processes -- and especially
  on the intersection of the two, which is sometimes called "digital
  twins". His research has generated over 150 internationally
  peer-reviewed [[link:/research/publications/][publications]], driven by leadership roles in research
  grants worth over €30M -- most recently as part of a £5M
  EPSRC-funded programme grant in the [[http://www.dcs.gla.ac.uk/research/S4/][Science of Sensor Systems
  Software]] He has served, amongst other activities, on the steering
  committee of the ACSOS conference; as programme and general chairs
  for the IEEE International Conference on Autonomic Computing; as an
  associate editor of ACM Transactions on Autonomous and Adaptive
  Systems; as a member of the executive of [[https://www.theiet.org/impact-society/thought-leadership/expert-panels/uk-computing-research-committee-ukcrc/][UKCRC]], the expert committee
  on UK computing research; as the chair of the BCS Distinguished PhD
  Dissertations award panel; and on the programme committees of a wide
  range of leading international conferences and specialised
  workshops. He was a director and vice-president of the [[http://www.ercim.org/][European
  Research Consortium for Informatics and Mathematics]] from 2006 --
  2009, and has served on a number of national and EU committees and
  strategic initiatives.

  Simon has previously worked at the [[https://www.stfc.ac.uk][UK STFC‘s Rutherford Appleton
  Laboratory]]; at [[https://www.trcd.ie][Trinity College Dublin]] and [[https://www.ucd.ie][UCD Dublin]] in Ireland;
  and was also the founder and CEO of Aurium, a research-led
  Dublin-based start-up company. He holds a BSc from the [[https://www.newcastle.ac.uk][University of
  Newcastle upon Tyne]] and DPhil from the [[https://www.york.ac.uk][University of York]], both in
  computer science, is a [[https://www.engc.org.uk/][Chartered Engineer]] and a Fellow of the
  [[https://www.bcs.org.uk][British Computer Society]].

  (See also my [[link:/short-cv.pdf][2-page]] and [[link:/medium-cv.pdf][complete]] CVs.)

  [[link:/personal/contact/][Contact details]]

* Other personal stuff

  Some of my [[link:/galleries/][photography]] appears here occasionally.
