* Nembes

  NEMBES -- Networks embedded systems in the built environment -- was a
  project funded in Ireland to explore how to improve building
  performance and building.  It involved researchers from Trinity
  College, UCD, Cork IT, the Tyndall Institute, and others institutions.

  The consortium was an interesting mix of hardware engineers and
  software researchers, with very different ideas about what constituted
  "systems": indeed, one of the best parts of the project was in working
  out exactly what we all meant and how our ideas fitted together!

  Our part of the work mainly focused on sensor networks and their
  applications. We looked at robustness to errors, since that's a major
  issue for built structures. We also explored localisation using
  ultrasonic signals, which again are a great way to deal with
  in-building localisation built-into the infrastructure.

  With my colleague Kieran Delaney I also did some preparatory work on
  building materials "augmented" with computational elements. This idea
  built on the work on [amorphous
  computing](https://en.wikipedia.org/wiki/Amorphous_computing), but with
  computing elements included into physical materials. This opens-up a
  lot of opportunities, since the computing and the material become
  essentially inseparable; it's also challenging to consider how one
  would bind electronics to a physical material in a way that will
  survive some of the processes materials go through. (It was a surprise
  to learn exactly how hot concrete gets as it cures.) It's a topic that
  I'd like to go back to in terms of the approrpiate programming
  paradigms.


** Publications

   #+begin: sd/bibliography :key keywords :value NEMBES
   <<citeproc_bib_item_1>>Delaney, Kieran, and Simon Dobson. 2008. “Augmenting Materials to Build Cooperating Objects.” In /Ambient Intelligence with Microsystems: Augmented Materials and Smart Objects/, edited by Kieran Delaney, 18:19–46. Microsystems. Springer Verlag.

   <<citeproc_bib_item_2>>Dobson, Simon. 2008. “Co-Design for Context Awareness in Pervasive Systems.” In /Ambient Intelligence with Microsystems: Augmented Materials and Smart Objects/, edited by Kieran Delaney, 18:297–307. Microsystems. Springer Verlag.

   <<citeproc_bib_item_3>>Kamal, Abu Raihan M., Chris Bleakley, and Simon Dobson. 2012. “Congestion Mitigation Using in-Network Sensor Data Summarization.” In /Proceedings of the Ninth ACM International Symposium on Performance Evaluation of Wireless Ad Hoc, Sensor, and Ubiquitous Networks/, 93–100. Paphos, CY. https://dx.doi.org//10.1145/2387027.2387043.

   <<citeproc_bib_item_4>>———. 2013. “Packet-Level Attestation (PLA): a Framework for in-Network Sensor-Data Reliability.” /ACM Transactions on Sensor Networks/ 9 (2). https://dx.doi.org//10.1145/2422966.2422976.

   <<citeproc_bib_item_5>>———. 2014. “Failure Detection in Wireless Sensor Networks: A Sequence Based Dynamic Approach.” /ACM Transactions on Sensor Networks/ 10 (2). https://dx.doi.org//10.1145/2530526.

   <<citeproc_bib_item_6>>O’Neill, Eleanor, Kris McGlinn, Eoin Bailey, Simon Dobson, and Kevin McCarthy. 2009. “Application Development Using Modelling and Dynamical Systems Analysis.” In /Proceedings of the 1st International Workshop on Context-Aware Middleware and Services/, 18–23. Dublin, IE. https://simondobson.org/softcopy/iwcams-09.pdf.

   <<citeproc_bib_item_7>>Razzaque, M.A., and Simon Dobson. 2009. “Enhancement of Self-Organisation in Wireless Networking through a Cross-Layer Approach.” In /Proceedings of the 1st International Conference on Ad Hoc Networks/. Niagara Falls, CA. https://simondobson.org/softcopy/adhoc-09.pdf.

   <<citeproc_bib_item_8>>Razzaque, M.A., Simon Dobson, and Paddy Nixon. 2008. “Cross-Layer Self Routing: A Self-Managed Routing Approach for MANETs.” In /Proceedings of the 4th IEEE International Conference on Wireless and Mobile Computing, Networking and Communications/. Avignon, FR: IEEE Press. https://simondobson.org/softcopy/clsr-08.pdf.

   <<citeproc_bib_item_9>>Saad, Mohamed, Chris Bleakley, and Simon Dobson. 2011. “Robust High Accuracy Ultrasonic Range Measurement System.” /IEEE Transactions on Instrumentation and Measurement/ 60 (10): 3334–41. https://dx.doi.org//10.1109/TIM.2011.2128950.

   <<citeproc_bib_item_10>>Saad, Mohamed, Chris Bleakley, Tarig Ballal, and Simon Dobson. 2012. “High-Accuracy Reference-Free Ultrasonic Location Estimation.” /IEEE Transactions on Instrumentation and Measurement/ 61 (6): 1561–70. https://dx.doi.org//10.1109/TIM.2011.2181911.
   #+end:
