# -*- org-attach-id-dir: "../../../../files/attachments"; -*-
#+BEGIN_COMMENT
.. title: Modern Common Lisp with FSet
.. slug: modern-common-lisp-with-fset
.. date: 2026-06-12 09:56:40 UTC+01:00
.. tags: project:lisp-bibliography, lisp, advanced-tutorial
.. category:
.. link:
.. description:
.. type: text

#+END_COMMENT
* Modern Common Lisp with FSet                                    :PUBLISHED:
  :PROPERTIES:
  :PUBLISHED-SOURCE: [[~/programming/simoninireland.github.io/posts/2026/06/12/modern-common-lisp-with-fset.org][modern-common-lisp-with-fset]]
  :PUBLISHED-URL: https://simondobson.org/2026/06/12/modern-common-lisp-with-fset
  :END:

  https://fset.common-lisp.dev/Modern-CL/Top_html/index.html

  A book-length description of a library, [[https://github.com/slburson/fset][FSet]], that provides
  functional collections for Lisp. By "functional collections" the
  author means collections -- sets, trees, maps, and others -- where
  update always produces a new collection rather than mutating the
  original collection in place. This is an attractive property for a
  language, and one that's hard to do efficiently. As with [[link:/2024/09/27/purely-functional-data-structures/][Purely
  functional data structures]], it provides a change of emphasis that
  makes for more referentially transparent code.

  The book contains a lot of discussion about the library's
  rationale and design, which makes it useful as a reference for
  others designing large libraries (or new languages, which of course
  in Lisp can mean much the same thing). There's an equally
  important discussion about what's /not/ provided (for example lazy
  collections) which is really interesting by giving an example of
  when to stop with a codebase that could otherwise probably grow
  indefinitely.
