# -*- org-attach-id-dir: "../../../../files/attachments"; -*-
#+BEGIN_COMMENT
.. title: TIL: The most powerful one-line program in the world
.. slug: til-the-most-powerful-one-line-program-in-the-world
.. date: 2024-07-17 10:20:53 UTC+01:00
.. tags: apl,programming,til
.. category:
.. link:
.. description:
.. type: text

#+END_COMMENT

* TIL: The most powerful one-line program in the world

  Well, the most powerful I've found so far, anyway.

  Given my current obsession with [[link:/categories/lisp/][Lisp]] you might reasonably expect it
  to be in that language. But it isn't: it's in [[https://en.wikipedia.org/wiki/APL_(programming_language)][APL]], and it performs
  one complete generation of [[https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life][Conway' Game of Life]] in one line of code:

  #+begin_src apl
Life←{↑↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}
  #+end_src

  ...and does so inexplicably to anyone who doesn't know APL,
  obviously, but the [[https://aplwiki.com/wiki/John_Scholes%27_Conway%27s_Game_of_Life][basic algorithm]] is simple:

  1. Take an array with 1 in each occupied cell and 0 elsewhere
  2. Build four new arrays by exchanging each element with its
     neighbour up, down, left, and right
  3. Sum these arrays, which places the number of neighbours into each cell
  4. Cut-off these values to be 1 if the cell has a value of 3 or 4,
     and 0 otherwise
  5. Re-format the arrays back into the starting configuration


  I checked it out using [[https://www.gnu.org/software/apl/][GNU APL]] and it works fine.

  I discovered this gem by accident, actually implemented [[https://github.com/chmykh/apl-life][in APL in
  Forth]] where someone has developed APL as an embedded DSL within
  [[https://en.wikipedia.org/wiki/Forth_(programming_language)][Forth]] (another language with which I have history). After a bit of
  digging I found a similar APL in Lisp, [[https://github.com/phantomics/april][April]], which clearly needs
  exploring.

  In many ways APL and Lisp are parallel tracks within programming
  language evolution, taking a single data structure (lists or arrays)
  and providing powerful ways to manipulate them. Lisp of course has
  been extended with other data structures, including arrays, which
  makes the fusion of array- and list-based programming rather
  attractive.

  I can't help asking myself what would have happened if APL hadn't
  fallen by the wayside. (I think this was inevitable, incidentally,
  once the syntax became fixed: any language that requires its own
  character set was always going to struggle.) We now have huge
  applications for array processing, from graphics to machine
  learning, and GPUs are from one perspective just APL accelerator
  co-processors. The ideas are still massively relevant.
